std = "selene_definitions"

[config]
# Allow for `_G.__DEV__` (etc) with packages like React-lua
global_usage = { ignore_pattern = "^__" }
empty_if = { comments_count = false }

[rules]
global_usage = "allow"
